#!/usr/bin/env python

import os

HOME = os.path.expanduser('~')
CURRENTPATH = os.path.dirname(os.path.abspath(__file__))

bashrc = (os.path.join(CURRENTPATH, '.bashrc'), os.path.join(HOME, '.bashrc'))
vimrc = (os.path.join(CURRENTPATH, 'vim-dotfiles/.vimrc'), os.path.join(HOME, '.vimrc'))
vimdotfiles = (os.path.join(CURRENTPATH, 'vim-dotfiles'), os.path.join(HOME, '.vim'))
zshrc = (os.path.join(CURRENTPATH, 'oh-my-zsh/.zshrc'), os.path.join(HOME, '.zshrc'))
ohmyzsh = (os.path.join(CURRENTPATH, 'oh-my-zsh'), os.path.join(HOME, '.oh-my-zsh'))

os.symlink(*bashrc)
os.symlink(*vimrc)
os.symlink(*vimdotfiles)
os.symlink(*zshrc)
os.symlink(*ohmyzsh)
