#!/usr/bin/env python3

import os
from os.path import lexists, islink, realpath

HOME = os.path.expanduser('~')
CURRENTPATH = os.path.dirname(os.path.abspath(__file__))

def makelink(paths):
    try:
        if lexists(paths[1]):
            if islink(paths[1]) and realpath(paths[1]) == paths[0]:
                print('Symbolic link for {0} already in place at {1}.'.format(realpath(paths[1]), paths[1]))
            elif realpath(paths[1]) == paths[0]:
                print('Incorrect symbolic link at {0} points to {1}.'.format(paths[1], paths[0]))
            else:
                print('A file already exists at {0}.'.format(paths[1]))
        else:
            os.symlink(*paths)
    except:
        print('An exception occurred for {0}:{1}: {2} {3} {4}'.format(paths[0], paths[1], lexists(paths[1]), islink(paths[1]), realpath(paths[1])))

bashrc = (os.path.join(CURRENTPATH, '.bashrc'), os.path.join(HOME, '.bashrc'))
vimrc = (os.path.join(CURRENTPATH, 'vim-dotfiles/.vimrc'), os.path.join(HOME, '.vimrc'))
vimdotfiles = (os.path.join(CURRENTPATH, 'vim-dotfiles'), os.path.join(HOME, '.vim'))
zshrc = (os.path.join(CURRENTPATH, '.zshrc'), os.path.join(HOME, '.zshrc'))
ohmyzsh = (os.path.join(CURRENTPATH, 'oh-my-zsh'), os.path.join(HOME, '.oh-my-zsh'))

makelink(bashrc)
makelink(vimrc)
makelink(vimdotfiles)
makelink(zshrc)
makelink(ohmyzsh)
